CREATE TABLE public.classification (
    classification_id INT GENERATED ALWAYS AS IDENTITY,
    classification_name VARCHAR(50) NOT NULL UNIQUE,
    CONSTRAINT classification_pk PRIMARY KEY (classification_id)
);
CREATE TABLE public.inventory (
    inv_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    inv_make VARCHAR(50) NOT NULL,
    inv_model VARCHAR(50) NOT NULL,
    inv_year INT NOT NULL,
    inv_description TEXT,
    inv_image VARCHAR(255),
    inv_thumbnail VARCHAR(255),
    inv_price NUMERIC(10,2) NOT NULL,
    inv_miles INT,
    inv_color VARCHAR(30),
    classification_id INT NOT NULL,
    CONSTRAINT fk_classification
        FOREIGN KEY(classification_id)
        REFERENCES public.classification(classification_id)
        ON DELETE CASCADE
);



CREATE TABLE IF NOT EXISTS public.account
(
    account_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    account_firstname character varying NOT NULL,
    account_lastname character varying NOT NULL,
    account_email character varying NOT NULL,
    account_password character varying NOT NULL,
    account_type account_type NOT NULL DEFAULT 'Client'::account_type,
    CONSTRAINT account_pkey PRIMARY KEY (account_id)
);