CREATE TYPE account_type AS ENUM ('Client', 'Admin', 'Employee');

CREATE TABLE IF NOT EXISTS classification (
  classification_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  classification_name character varying NOT NULL,
  CONSTRAINT classification_pkey PRIMARY KEY (classification_id)
);

CREATE TABLE IF NOT EXISTS inventory (
  inv_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  inv_make character varying NOT NULL,
  inv_model character varying NOT NULL,
  inv_description text NOT NULL,
  inv_image character varying NOT NULL,
  inv_thumbnail character varying NOT NULL,
  inv_price numeric NOT NULL,
  inv_year integer NOT NULL,
  inv_miles integer NOT NULL,
  inv_color character varying NOT NULL,
  classification_id integer NOT NULL,
  CONSTRAINT inventory_pkey PRIMARY KEY (inv_id)
);

ALTER TABLE inventory
ADD CONSTRAINT fk_classification
FOREIGN KEY (classification_id)
REFERENCES classification (classification_id);

CREATE TABLE IF NOT EXISTS account (
  account_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  account_firstname character varying NOT NULL,
  account_lastname character varying NOT NULL,
  account_email character varying NOT NULL,
  account_password character varying NOT NULL,
  account_type account_type NOT NULL DEFAULT 'Client',
  CONSTRAINT account_pkey PRIMARY KEY (account_id)
);

INSERT INTO classification (classification_name) VALUES
('Sport'),
('SUV'),
('Truck'),
('Sedan');

INSERT INTO inventory (
  inv_make, inv_model, inv_description, inv_image, inv_thumbnail,
  inv_price, inv_year, inv_miles, inv_color, classification_id
)
VALUES
('GM', 'Hummer', 'small interiors', '/images/hummer.jpg', '/images/hummer-tn.jpg', 55000, 2020, 12000, 'Black', 1),
('Ford', 'Mustang', 'fast sports car', '/images/mustang.jpg', '/images/mustang-tn.jpg', 48000, 2021, 8000, 'Red', 1);

-- Update description
UPDATE inventory
SET inv_description = REPLACE(inv_description, 'small interiors', 'a huge interior')
WHERE inv_make = 'GM' AND inv_model = 'Hummer';

-- Update image paths
UPDATE inventory
SET 
  inv_image = REPLACE(inv_image, '/images/', '/images/vehicles/'),
  inv_thumbnail = REPLACE(inv_thumbnail, '/images/', '/images/vehicles/');
